---
name: "CI - Maven Build"

on:
  - "push"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
      - name: "Setup JDK 25"
        uses: "actions/setup-java@v5"
        with:
          java-version: "25"
          distribution: "temurin"
      - name: "Run maven clean package"
        run: "./mvnw --batch-mode clean package"
